### ISSUE TITLE
llama checkpoints

### ISSUE THREAD

**Issue by OfficerChul** [scale-lab/PoliTune#1]
Hi, I am wondering how to download checkpoints?

in `llama8b_lora_dpo_single_device.yaml` file, 
there is a
```
# Tokenizer
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: checkpoints/Meta-Llama-3-8B-Instruct/original/tokenizer.model
```
file which means that I need a checkpoints directory, but I cannot find it on your project.

I am very appreciated if you can let me know the solution.
